### ISSUE TITLE
On debian jessie can't add new repos 

### ISSUE THREAD

**Issue by rubemlrm** [fubarhouse/docker-ansible#1]
Hi there, first of all great work you've done with this project been using some of your images. And they work very well, but using the debian jessie when i add a new repo with the apt_repository module i'm getting the following error: 

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The method driver /usr/lib/apt/methods/https could not be found.`

my apt_repository command have the following information:
```yaml
    - name: Add gpg keys
      apt_key:
        url: '{{ item }}'
        state: 'present'
      with_items:
        - 'https://download.docker.com/linux/debian/gpg'
    - name: Add repos
      apt_repository:
        repo: '{{ item }}'
        state: 'present'
      with_items:
        - 'deb [arch={{arch}}] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable'
```

And for what i've searched this happens because the missing of this packages **apt-transport-https ca-certificates**

Another note for my tests i'm using besides the jessie debian , the stretch release to, and in the stretch release all work as it should.

Thanks in advance and keep the good work.
